// GENERATED by the workspace tooling. Do not edit.
import { deployContract, findDeployedContract } from '@midnight-ntwrk/midnight-js-contracts';
import type { TxData, SchnorrSignature } from './types.js';
export type * from './types.js';

type CallResult = { public: { txId: string; txHash: string; blockHeight: number } };
type Found = { callTx: Record<string, (...a: any[]) => Promise<CallResult>>; deployTxData: { public: { contractAddress: string } } };

const toTxData = (r: CallResult): TxData => ({ txId: String(r.public.txId), txHash: r.public.txHash, blockHeight: r.public.blockHeight });

/** Typed wrapper over midnight-js callTx for fungible-token-v2.6. */
export class FungibleTokenV26Client {
  private constructor(private readonly found: Found) {}

  static async deploy(providers: unknown, compiledContract: unknown, args: unknown[]): Promise<FungibleTokenV26Client> {
    const found = await (deployContract as any)(providers, { compiledContract, args });
    return new FungibleTokenV26Client(found as Found);
  }

  static async connect(providers: unknown, compiledContract: unknown, contractAddress: string): Promise<FungibleTokenV26Client> {
    const found = await (findDeployedContract as any)(providers, { compiledContract, contractAddress });
    return new FungibleTokenV26Client(found as Found);
  }

  get contractAddress(): string {
    return this.found.deployTxData.public.contractAddress;
  }

  /** Calls circuit `mint`. */
  async mint(to: Uint8Array, value: bigint, pubkeys: JubjubPoint[], signatures: SchnorrSignature[]): Promise<TxData> {
    return toTxData(await this.found.callTx.mint(to, value, pubkeys, signatures));
  }

  /** Calls circuit `burn`. */
  async burn(account: Uint8Array, value: bigint, pubkeys: JubjubPoint[], signatures: SchnorrSignature[]): Promise<TxData> {
    return toTxData(await this.found.callTx.burn(account, value, pubkeys, signatures));
  }

  /** Calls circuit `setEmergencyPauser`. */
  async setEmergencyPauser(newPauser: Uint8Array, pubkeys: JubjubPoint[], signatures: SchnorrSignature[]): Promise<TxData> {
    return toTxData(await this.found.callTx.setEmergencyPauser(newPauser, pubkeys, signatures));
  }

  /** Calls circuit `adminReallocate`. */
  async adminReallocate(trappedAccount: Uint8Array, targetSpendableAccount: Uint8Array, amount: bigint, pubkeys: JubjubPoint[], signatures: SchnorrSignature[]): Promise<TxData> {
    return toTxData(await this.found.callTx.adminReallocate(trappedAccount, targetSpendableAccount, amount, pubkeys, signatures));
  }

  /** Calls circuit `rotateSigner`. */
  async rotateSigner(oldSignerCommitment: Uint8Array, newSignerPubkey: JubjubPoint, newSignerPop: SchnorrSignature, pubkeys: JubjubPoint[], signatures: SchnorrSignature[]): Promise<TxData> {
    return toTxData(await this.found.callTx.rotateSigner(oldSignerCommitment, newSignerPubkey, newSignerPop, pubkeys, signatures));
  }

  /** Calls circuit `pause`. */
  async pause(caller: Uint8Array): Promise<TxData> {
    return toTxData(await this.found.callTx.pause(caller));
  }

  /** Calls circuit `unpause`. */
  async unpause(caller: Uint8Array): Promise<TxData> {
    return toTxData(await this.found.callTx.unpause(caller));
  }

  /** Calls circuit `transfer`. */
  async transfer(caller: Uint8Array, to: Uint8Array, value: bigint): Promise<TxData> {
    return toTxData(await this.found.callTx.transfer(caller, to, value));
  }

  /** Calls circuit `approve`. */
  async approve(caller: Uint8Array, spender: Uint8Array, value: bigint): Promise<TxData> {
    return toTxData(await this.found.callTx.approve(caller, spender, value));
  }

  /** Calls circuit `transferFrom`. */
  async transferFrom(caller: Uint8Array, fromAccount: Uint8Array, to: Uint8Array, value: bigint): Promise<TxData> {
    return toTxData(await this.found.callTx.transferFrom(caller, fromAccount, to, value));
  }

  /** Calls circuit `selfBurn`. */
  async selfBurn(caller: Uint8Array, value: bigint): Promise<TxData> {
    return toTxData(await this.found.callTx.selfBurn(caller, value));
  }

  /** Calls circuit `emergencyWithdraw`. */
  async emergencyWithdraw(caller: Uint8Array, amount: bigint): Promise<TxData> {
    return toTxData(await this.found.callTx.emergencyWithdraw(caller, amount));
  }
}
