// GENERATED by the workspace tooling from fungible-token-v2.6 (compiler 0.31.1, language 0.23.0). Do not edit.
import type { JubjubPoint } from '@midnight-ntwrk/compact-runtime';

export type { JubjubPoint };
export interface SchnorrSignature { announcement: JubjubPoint; response: bigint }

export interface TxData {
  txId: string;
  txHash: string;
  blockHeight: number;
}
