/** Maps compiler `contract-info.json` types to TypeScript. Pure, used by SDK/test generators. */
export interface InfoType {
  'type-name': string;
  length?: number;
  name?: string;
  type?: InfoType;
  types?: InfoType[];
  elements?: { name: string; type: InfoType }[];
  maxval?: number | string;
  tsType?: string;
}

export function tsType(t: InfoType): string {
  switch (t['type-name']) {
    case 'Bytes':
      return 'Uint8Array';
    case 'Uint':
    case 'Field':
      return 'bigint';
    case 'Boolean':
      return 'boolean';
    case 'JubjubPoint':
      return 'JubjubPoint';
    case 'Opaque':
      return t.tsType ?? 'unknown';
    case 'Vector':
      return `${tsType(t.type!)}[]`;
    case 'Tuple':
      return `[${(t.types ?? []).map(tsType).join(', ')}]`;
    case 'Struct':
      return t.name ?? 'unknown';
    case 'Alias':
      return t.type ? tsType(t.type) : 'unknown';
    default:
      return 'unknown';
  }
}

export interface InfoCircuit {
  name: string;
  pure: boolean;
  proof: boolean;
  arguments: { name: string; type: InfoType }[];
  'result-type'?: InfoType;
  'result type'?: InfoType;
}

export interface ContractInfo {
  'compiler-version': string;
  'language-version': string;
  'runtime-version': string;
  circuits: InfoCircuit[];
  witnesses: { name: string }[];
}

/** SDK header + one typed method per impure (provable) circuit. */
export function generateSdkSource(info: ContractInfo, contractName: string, managedRelFromSdk: string): Record<string, string> {
  const circuits = info.circuits.filter((c) => !c.pure);
  const structs = new Map<string, string>();
  const collect = (t: InfoType) => {
    if (t['type-name'] === 'Struct' && t.name && t.elements) {
      structs.set(t.name, `export interface ${t.name} { ${t.elements.map((e) => `${e.name}: ${tsType(e.type)}`).join('; ')} }`);
      t.elements.forEach((e) => collect(e.type));
    }
    if (t.type) collect(t.type);
  };
  circuits.forEach((c) => c.arguments.forEach((a) => collect(a.type)));

  const methods = circuits
    .map((c) => {
      const params = c.arguments.map((a) => `${a.name}: ${tsType(a.type)}`).join(', ');
      const args = c.arguments.map((a) => a.name).join(', ');
      return `  /** Calls circuit \`${c.name}\`. */\n  async ${c.name}(${params}): Promise<TxData> {\n    return toTxData(await this.found.callTx.${c.name}(${args}));\n  }`;
    })
    .join('\n\n');

  const types = `// GENERATED by the workspace tooling from ${contractName} (compiler ${info['compiler-version']}, language ${info['language-version']}). Do not edit.
import type { JubjubPoint } from '@midnight-ntwrk/compact-runtime';

export type { JubjubPoint };
${[...structs.values()].join('\n')}

export interface TxData {
  txId: string;
  txHash: string;
  blockHeight: number;
}
`;

  const client = `// GENERATED by the workspace tooling. Do not edit.
import { deployContract, findDeployedContract } from '@midnight-ntwrk/midnight-js-contracts';
import type { JubjubPoint, TxData${[...structs.keys()].map((s) => `, ${s}`).join('')} } from './types.js';
export type * from './types.js';

type CallResult = { public: { txId: string; txHash: string; blockHeight: number } };
type Found = { callTx: Record<string, (...a: any[]) => Promise<CallResult>>; deployTxData: { public: { contractAddress: string } } };

const toTxData = (r: CallResult): TxData => ({ txId: String(r.public.txId), txHash: r.public.txHash, blockHeight: r.public.blockHeight });

/** Typed wrapper over midnight-js callTx for ${contractName}. */
export class ${pascal(contractName)}Client {
  private constructor(private readonly found: Found) {}

  static async deploy(providers: unknown, compiledContract: unknown, args: unknown[]): Promise<${pascal(contractName)}Client> {
    const found = await (deployContract as any)(providers, { compiledContract, args });
    return new ${pascal(contractName)}Client(found as Found);
  }

  static async connect(providers: unknown, compiledContract: unknown, contractAddress: string): Promise<${pascal(contractName)}Client> {
    const found = await (findDeployedContract as any)(providers, { compiledContract, contractAddress });
    return new ${pascal(contractName)}Client(found as Found);
  }

  get contractAddress(): string {
    return this.found.deployTxData.public.contractAddress;
  }

${methods}
}
`;
  const index = `// GENERATED. Re-exports the compiled contract module and the typed client.
export * from './client.js';
// Named re-exports: the contract module also declares \`SchnorrSignature\`, which client.ts already exports.
export { Contract, ledger, pureCircuits } from '${managedRelFromSdk}/contract/index.js';
export type { Ledger, Witnesses, ImpureCircuits, PureCircuits, Circuits } from '${managedRelFromSdk}/contract/index.js';
`;
  return { 'types.ts': types, 'client.ts': client, 'index.ts': index };
}

const pascal = (s: string) => s.replace(/(^|[^a-zA-Z0-9]+)([a-zA-Z0-9])/g, (_m, _p, c: string) => c.toUpperCase());

/** One test per circuit: existence, arity, and purity flags derived from compiler metadata. */
export function generateTestSource(info: ContractInfo, contractName: string, managedRel: string): string {
  const cases = info.circuits
    .map((c) => {
      const kind = c.pure ? 'pure' : 'impure';
      return `  it('${c.name} is exposed as a ${kind} circuit with ${c.arguments.length} argument(s)', () => {
    const c = meta.circuits.find((x) => x.name === '${c.name}');
    expect(c).toBeDefined();
    expect(c!.pure).toBe(${c.pure});
    expect(c!.arguments).toHaveLength(${c.arguments.length});
    ${c.pure ? `expect(typeof pureCircuits.${c.name}).toBe('function');` : `expect(typeof contract.impureCircuits.${c.name}).toBe('function');`}
  });`;
    })
    .join('\n\n');
  return `// GENERATED by the workspace tooling from ${contractName}. Regenerate rather than edit.
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { describe, expect, it } from 'vitest';
import { Contract, pureCircuits } from '${managedRel}/contract/index.js';

const meta = JSON.parse(
  readFileSync(resolve(__dirname, '${managedRel}/compiler/contract-info.json'), 'utf8')
) as { circuits: { name: string; pure: boolean; arguments: unknown[] }[]; witnesses: { name: string }[] };

const contract = new Contract({
  localSecretKey: (c: { privateState: unknown }) => [c.privateState, new Uint8Array(32)],
  getSchnorrReduction: (c: { privateState: unknown }) => [c.privateState, [0n, 0n]]
} as never);

describe('${contractName} generated interface checks', () => {
  it('declares compiler ${info['compiler-version']} metadata', () => {
    expect(meta.circuits.length).toBe(${info.circuits.length});
  });

${cases}
});
`;
}
